/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as BookRouteImport } from './routes/book'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as CreateClinicRouteImport } from './routes/create-clinic'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as PublicFaqRouteImport } from './routes/_public/faq'
import { Route as AuthenticatedAdminAppointmentsRouteImport } from './routes/_authenticated/admin/appointments'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminDoctorsRouteImport } from './routes/_authenticated/admin/doctors'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin/notifications'
import { Route as AuthenticatedAdminPatientsRouteImport } from './routes/_authenticated/admin/patients'
import { Route as AuthenticatedAdminQueueRouteImport } from './routes/_authenticated/admin/queue'
import { Route as AuthenticatedAdminRoomsRouteImport } from './routes/_authenticated/admin/rooms'
import { Route as AuthenticatedAdminScheduleRouteImport } from './routes/_authenticated/admin/schedule'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminStaffRouteImport } from './routes/_authenticated/admin/staff'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as PublicDoctorsIndexRouteImport } from './routes/_public/doctors/index'
import { Route as PublicDoctorsDoctorIdRouteImport } from './routes/_public/doctors/$doctorId'
import { Route as AuthenticatedAdminSettingsIndexRouteImport } from './routes/_authenticated/admin/settings.index'
import { Route as AuthenticatedAdminSettingsAccountRouteImport } from './routes/_authenticated/admin/settings.account'
import { Route as AuthenticatedAdminSettingsAppearanceRouteImport } from './routes/_authenticated/admin/settings.appearance'
import { Route as AuthenticatedAdminSettingsDisplayRouteImport } from './routes/_authenticated/admin/settings.display'
import { Route as AuthenticatedAdminSettingsFacilityRouteImport } from './routes/_authenticated/admin/settings.facility'
import { Route as AuthenticatedAdminSettingsNotificationsRouteImport } from './routes/_authenticated/admin/settings.notifications'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateClinicRoute = CreateClinicRouteImport.update({
  id: '/create-clinic',
  path: '/create-clinic',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicFaqRoute = PublicFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthenticatedAdminAppointmentsRoute =
  AuthenticatedAdminAppointmentsRouteImport.update({
    id: '/admin/appointments',
    path: '/admin/appointments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDoctorsRoute =
  AuthenticatedAdminDoctorsRouteImport.update({
    id: '/admin/doctors',
    path: '/admin/doctors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/admin/notifications',
    path: '/admin/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPatientsRoute =
  AuthenticatedAdminPatientsRouteImport.update({
    id: '/admin/patients',
    path: '/admin/patients',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminQueueRoute = AuthenticatedAdminQueueRouteImport.update({
  id: '/admin/queue',
  path: '/admin/queue',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoomsRoute = AuthenticatedAdminRoomsRouteImport.update({
  id: '/admin/rooms',
  path: '/admin/rooms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminScheduleRoute =
  AuthenticatedAdminScheduleRouteImport.update({
    id: '/admin/schedule',
    path: '/admin/schedule',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminStaffRoute = AuthenticatedAdminStaffRouteImport.update({
  id: '/admin/staff',
  path: '/admin/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const PublicDoctorsIndexRoute = PublicDoctorsIndexRouteImport.update({
  id: '/doctors/',
  path: '/doctors/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicDoctorsDoctorIdRoute = PublicDoctorsDoctorIdRouteImport.update({
  id: '/doctors/$doctorId',
  path: '/doctors/$doctorId',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthenticatedAdminSettingsIndexRoute =
  AuthenticatedAdminSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminSettingsRoute,
  } as any)
const AuthenticatedAdminSettingsAccountRoute =
  AuthenticatedAdminSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedAdminSettingsRoute,
  } as any)
const AuthenticatedAdminSettingsAppearanceRoute =
  AuthenticatedAdminSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedAdminSettingsRoute,
  } as any)
const AuthenticatedAdminSettingsDisplayRoute =
  AuthenticatedAdminSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedAdminSettingsRoute,
  } as any)
const AuthenticatedAdminSettingsFacilityRoute =
  AuthenticatedAdminSettingsFacilityRouteImport.update({
    id: '/facility',
    path: '/facility',
    getParentRoute: () => AuthenticatedAdminSettingsRoute,
  } as any)
const AuthenticatedAdminSettingsNotificationsRoute =
  AuthenticatedAdminSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/book': typeof BookRoute
  '/change-password': typeof ChangePasswordRoute
  '/check-in': typeof CheckInRoute
  '/create-clinic': typeof CreateClinicRoute
  '/patient': typeof PatientRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/faq': typeof PublicFaqRoute
  '/admin/appointments': typeof AuthenticatedAdminAppointmentsRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/doctors': typeof AuthenticatedAdminDoctorsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/patients': typeof AuthenticatedAdminPatientsRoute
  '/admin/queue': typeof AuthenticatedAdminQueueRoute
  '/admin/rooms': typeof AuthenticatedAdminRoomsRoute
  '/admin/schedule': typeof AuthenticatedAdminScheduleRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRouteWithChildren
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/doctors/$doctorId': typeof PublicDoctorsDoctorIdRoute
  '/doctors/': typeof PublicDoctorsIndexRoute
  '/admin/settings/account': typeof AuthenticatedAdminSettingsAccountRoute
  '/admin/settings/appearance': typeof AuthenticatedAdminSettingsAppearanceRoute
  '/admin/settings/display': typeof AuthenticatedAdminSettingsDisplayRoute
  '/admin/settings/facility': typeof AuthenticatedAdminSettingsFacilityRoute
  '/admin/settings/notifications': typeof AuthenticatedAdminSettingsNotificationsRoute
  '/admin/settings/': typeof AuthenticatedAdminSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/book': typeof BookRoute
  '/change-password': typeof ChangePasswordRoute
  '/check-in': typeof CheckInRoute
  '/create-clinic': typeof CreateClinicRoute
  '/patient': typeof PatientRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/faq': typeof PublicFaqRoute
  '/admin/appointments': typeof AuthenticatedAdminAppointmentsRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/doctors': typeof AuthenticatedAdminDoctorsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/patients': typeof AuthenticatedAdminPatientsRoute
  '/admin/queue': typeof AuthenticatedAdminQueueRoute
  '/admin/rooms': typeof AuthenticatedAdminRoomsRoute
  '/admin/schedule': typeof AuthenticatedAdminScheduleRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/doctors/$doctorId': typeof PublicDoctorsDoctorIdRoute
  '/doctors': typeof PublicDoctorsIndexRoute
  '/admin/settings/account': typeof AuthenticatedAdminSettingsAccountRoute
  '/admin/settings/appearance': typeof AuthenticatedAdminSettingsAppearanceRoute
  '/admin/settings/display': typeof AuthenticatedAdminSettingsDisplayRoute
  '/admin/settings/facility': typeof AuthenticatedAdminSettingsFacilityRoute
  '/admin/settings/notifications': typeof AuthenticatedAdminSettingsNotificationsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/book': typeof BookRoute
  '/change-password': typeof ChangePasswordRoute
  '/check-in': typeof CheckInRoute
  '/create-clinic': typeof CreateClinicRoute
  '/patient': typeof PatientRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/_public/about': typeof PublicAboutRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/faq': typeof PublicFaqRoute
  '/_public/': typeof PublicIndexRoute
  '/_authenticated/admin/appointments': typeof AuthenticatedAdminAppointmentsRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/doctors': typeof AuthenticatedAdminDoctorsRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/patients': typeof AuthenticatedAdminPatientsRoute
  '/_authenticated/admin/queue': typeof AuthenticatedAdminQueueRoute
  '/_authenticated/admin/rooms': typeof AuthenticatedAdminRoomsRoute
  '/_authenticated/admin/schedule': typeof AuthenticatedAdminScheduleRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRouteWithChildren
  '/_authenticated/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_public/doctors/$doctorId': typeof PublicDoctorsDoctorIdRoute
  '/_public/doctors/': typeof PublicDoctorsIndexRoute
  '/_authenticated/admin/settings/account': typeof AuthenticatedAdminSettingsAccountRoute
  '/_authenticated/admin/settings/appearance': typeof AuthenticatedAdminSettingsAppearanceRoute
  '/_authenticated/admin/settings/display': typeof AuthenticatedAdminSettingsDisplayRoute
  '/_authenticated/admin/settings/facility': typeof AuthenticatedAdminSettingsFacilityRoute
  '/_authenticated/admin/settings/notifications': typeof AuthenticatedAdminSettingsNotificationsRoute
  '/_authenticated/admin/settings/': typeof AuthenticatedAdminSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/change-password'
    | '/check-in'
    | '/create-clinic'
    | '/patient'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/about'
    | '/contact'
    | '/faq'
    | '/admin/appointments'
    | '/admin/dashboard'
    | '/admin/doctors'
    | '/admin/notifications'
    | '/admin/patients'
    | '/admin/queue'
    | '/admin/rooms'
    | '/admin/schedule'
    | '/admin/settings'
    | '/admin/staff'
    | '/errors/$error'
    | '/doctors/$doctorId'
    | '/doctors/'
    | '/admin/settings/account'
    | '/admin/settings/appearance'
    | '/admin/settings/display'
    | '/admin/settings/facility'
    | '/admin/settings/notifications'
    | '/admin/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/change-password'
    | '/check-in'
    | '/create-clinic'
    | '/patient'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/about'
    | '/contact'
    | '/faq'
    | '/admin/appointments'
    | '/admin/dashboard'
    | '/admin/doctors'
    | '/admin/notifications'
    | '/admin/patients'
    | '/admin/queue'
    | '/admin/rooms'
    | '/admin/schedule'
    | '/admin/staff'
    | '/errors/$error'
    | '/doctors/$doctorId'
    | '/doctors'
    | '/admin/settings/account'
    | '/admin/settings/appearance'
    | '/admin/settings/display'
    | '/admin/settings/facility'
    | '/admin/settings/notifications'
    | '/admin/settings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/book'
    | '/change-password'
    | '/check-in'
    | '/create-clinic'
    | '/patient'
    | '/(auth)/forgot-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/_public/about'
    | '/_public/contact'
    | '/_public/faq'
    | '/_public/'
    | '/_authenticated/admin/appointments'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/doctors'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/patients'
    | '/_authenticated/admin/queue'
    | '/_authenticated/admin/rooms'
    | '/_authenticated/admin/schedule'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/staff'
    | '/_authenticated/errors/$error'
    | '/_public/doctors/$doctorId'
    | '/_public/doctors/'
    | '/_authenticated/admin/settings/account'
    | '/_authenticated/admin/settings/appearance'
    | '/_authenticated/admin/settings/display'
    | '/_authenticated/admin/settings/facility'
    | '/_authenticated/admin/settings/notifications'
    | '/_authenticated/admin/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  BookRoute: typeof BookRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  CheckInRoute: typeof CheckInRoute
  CreateClinicRoute: typeof CreateClinicRoute
  PatientRoute: typeof PatientRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-clinic': {
      id: '/create-clinic'
      path: '/create-clinic'
      fullPath: '/create-clinic'
      preLoaderRoute: typeof CreateClinicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/faq': {
      id: '/_public/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof PublicFaqRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_authenticated/admin/appointments': {
      id: '/_authenticated/admin/appointments'
      path: '/admin/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AuthenticatedAdminAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/doctors': {
      id: '/_authenticated/admin/doctors'
      path: '/admin/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof AuthenticatedAdminDoctorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/patients': {
      id: '/_authenticated/admin/patients'
      path: '/admin/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof AuthenticatedAdminPatientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/queue': {
      id: '/_authenticated/admin/queue'
      path: '/admin/queue'
      fullPath: '/admin/queue'
      preLoaderRoute: typeof AuthenticatedAdminQueueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/rooms': {
      id: '/_authenticated/admin/rooms'
      path: '/admin/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AuthenticatedAdminRoomsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/schedule': {
      id: '/_authenticated/admin/schedule'
      path: '/admin/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AuthenticatedAdminScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/staff': {
      id: '/_authenticated/admin/staff'
      path: '/admin/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AuthenticatedAdminStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_public/doctors/': {
      id: '/_public/doctors/'
      path: '/doctors'
      fullPath: '/doctors/'
      preLoaderRoute: typeof PublicDoctorsIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/doctors/$doctorId': {
      id: '/_public/doctors/$doctorId'
      path: '/doctors/$doctorId'
      fullPath: '/doctors/$doctorId'
      preLoaderRoute: typeof PublicDoctorsDoctorIdRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_authenticated/admin/settings/': {
      id: '/_authenticated/admin/settings/'
      path: '/'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AuthenticatedAdminSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminSettingsRoute
    }
    '/_authenticated/admin/settings/account': {
      id: '/_authenticated/admin/settings/account'
      path: '/account'
      fullPath: '/admin/settings/account'
      preLoaderRoute: typeof AuthenticatedAdminSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedAdminSettingsRoute
    }
    '/_authenticated/admin/settings/appearance': {
      id: '/_authenticated/admin/settings/appearance'
      path: '/appearance'
      fullPath: '/admin/settings/appearance'
      preLoaderRoute: typeof AuthenticatedAdminSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedAdminSettingsRoute
    }
    '/_authenticated/admin/settings/display': {
      id: '/_authenticated/admin/settings/display'
      path: '/display'
      fullPath: '/admin/settings/display'
      preLoaderRoute: typeof AuthenticatedAdminSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedAdminSettingsRoute
    }
    '/_authenticated/admin/settings/facility': {
      id: '/_authenticated/admin/settings/facility'
      path: '/facility'
      fullPath: '/admin/settings/facility'
      preLoaderRoute: typeof AuthenticatedAdminSettingsFacilityRouteImport
      parentRoute: typeof AuthenticatedAdminSettingsRoute
    }
    '/_authenticated/admin/settings/notifications': {
      id: '/_authenticated/admin/settings/notifications'
      path: '/notifications'
      fullPath: '/admin/settings/notifications'
      preLoaderRoute: typeof AuthenticatedAdminSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminSettingsRoute
    }
  }
}

interface AuthenticatedAdminSettingsRouteChildren {
  AuthenticatedAdminSettingsAccountRoute: typeof AuthenticatedAdminSettingsAccountRoute
  AuthenticatedAdminSettingsAppearanceRoute: typeof AuthenticatedAdminSettingsAppearanceRoute
  AuthenticatedAdminSettingsDisplayRoute: typeof AuthenticatedAdminSettingsDisplayRoute
  AuthenticatedAdminSettingsFacilityRoute: typeof AuthenticatedAdminSettingsFacilityRoute
  AuthenticatedAdminSettingsNotificationsRoute: typeof AuthenticatedAdminSettingsNotificationsRoute
  AuthenticatedAdminSettingsIndexRoute: typeof AuthenticatedAdminSettingsIndexRoute
}

const AuthenticatedAdminSettingsRouteChildren: AuthenticatedAdminSettingsRouteChildren =
  {
    AuthenticatedAdminSettingsAccountRoute:
      AuthenticatedAdminSettingsAccountRoute,
    AuthenticatedAdminSettingsAppearanceRoute:
      AuthenticatedAdminSettingsAppearanceRoute,
    AuthenticatedAdminSettingsDisplayRoute:
      AuthenticatedAdminSettingsDisplayRoute,
    AuthenticatedAdminSettingsFacilityRoute:
      AuthenticatedAdminSettingsFacilityRoute,
    AuthenticatedAdminSettingsNotificationsRoute:
      AuthenticatedAdminSettingsNotificationsRoute,
    AuthenticatedAdminSettingsIndexRoute: AuthenticatedAdminSettingsIndexRoute,
  }

const AuthenticatedAdminSettingsRouteWithChildren =
  AuthenticatedAdminSettingsRoute._addFileChildren(
    AuthenticatedAdminSettingsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminAppointmentsRoute: typeof AuthenticatedAdminAppointmentsRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminDoctorsRoute: typeof AuthenticatedAdminDoctorsRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminPatientsRoute: typeof AuthenticatedAdminPatientsRoute
  AuthenticatedAdminQueueRoute: typeof AuthenticatedAdminQueueRoute
  AuthenticatedAdminRoomsRoute: typeof AuthenticatedAdminRoomsRoute
  AuthenticatedAdminScheduleRoute: typeof AuthenticatedAdminScheduleRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRouteWithChildren
  AuthenticatedAdminStaffRoute: typeof AuthenticatedAdminStaffRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminAppointmentsRoute: AuthenticatedAdminAppointmentsRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminDoctorsRoute: AuthenticatedAdminDoctorsRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminPatientsRoute: AuthenticatedAdminPatientsRoute,
  AuthenticatedAdminQueueRoute: AuthenticatedAdminQueueRoute,
  AuthenticatedAdminRoomsRoute: AuthenticatedAdminRoomsRoute,
  AuthenticatedAdminScheduleRoute: AuthenticatedAdminScheduleRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRouteWithChildren,
  AuthenticatedAdminStaffRoute: AuthenticatedAdminStaffRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PublicRouteRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicFaqRoute: typeof PublicFaqRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicDoctorsDoctorIdRoute: typeof PublicDoctorsDoctorIdRoute
  PublicDoctorsIndexRoute: typeof PublicDoctorsIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicContactRoute: PublicContactRoute,
  PublicFaqRoute: PublicFaqRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicDoctorsDoctorIdRoute: PublicDoctorsDoctorIdRoute,
  PublicDoctorsIndexRoute: PublicDoctorsIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  BookRoute: BookRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  CheckInRoute: CheckInRoute,
  CreateClinicRoute: CreateClinicRoute,
  PatientRoute: PatientRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
